// Generated by gencpp from file nimo_end_effector/act_linear.msg
// DO NOT EDIT!


#ifndef NIMO_END_EFFECTOR_MESSAGE_ACT_LINEAR_H
#define NIMO_END_EFFECTOR_MESSAGE_ACT_LINEAR_H

#include <ros/service_traits.h>


#include <nimo_end_effector/act_linearRequest.h>
#include <nimo_end_effector/act_linearResponse.h>


namespace nimo_end_effector
{

struct act_linear
{

typedef act_linearRequest Request;
typedef act_linearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct act_linear
} // namespace nimo_end_effector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nimo_end_effector::act_linear > {
  static const char* value()
  {
    return "63835d95a9bc618eb2108b4cd1999061";
  }

  static const char* value(const ::nimo_end_effector::act_linear&) { return value(); }
};

template<>
struct DataType< ::nimo_end_effector::act_linear > {
  static const char* value()
  {
    return "nimo_end_effector/act_linear";
  }

  static const char* value(const ::nimo_end_effector::act_linear&) { return value(); }
};


// service_traits::MD5Sum< ::nimo_end_effector::act_linearRequest> should match
// service_traits::MD5Sum< ::nimo_end_effector::act_linear >
template<>
struct MD5Sum< ::nimo_end_effector::act_linearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nimo_end_effector::act_linear >::value();
  }
  static const char* value(const ::nimo_end_effector::act_linearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nimo_end_effector::act_linearRequest> should match
// service_traits::DataType< ::nimo_end_effector::act_linear >
template<>
struct DataType< ::nimo_end_effector::act_linearRequest>
{
  static const char* value()
  {
    return DataType< ::nimo_end_effector::act_linear >::value();
  }
  static const char* value(const ::nimo_end_effector::act_linearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nimo_end_effector::act_linearResponse> should match
// service_traits::MD5Sum< ::nimo_end_effector::act_linear >
template<>
struct MD5Sum< ::nimo_end_effector::act_linearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nimo_end_effector::act_linear >::value();
  }
  static const char* value(const ::nimo_end_effector::act_linearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nimo_end_effector::act_linearResponse> should match
// service_traits::DataType< ::nimo_end_effector::act_linear >
template<>
struct DataType< ::nimo_end_effector::act_linearResponse>
{
  static const char* value()
  {
    return DataType< ::nimo_end_effector::act_linear >::value();
  }
  static const char* value(const ::nimo_end_effector::act_linearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIMO_END_EFFECTOR_MESSAGE_ACT_LINEAR_H
