// Generated by gencpp from file nimo_end_effector/get_dat.msg
// DO NOT EDIT!


#ifndef NIMO_END_EFFECTOR_MESSAGE_GET_DAT_H
#define NIMO_END_EFFECTOR_MESSAGE_GET_DAT_H

#include <ros/service_traits.h>


#include <nimo_end_effector/get_datRequest.h>
#include <nimo_end_effector/get_datResponse.h>


namespace nimo_end_effector
{

struct get_dat
{

typedef get_datRequest Request;
typedef get_datResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_dat
} // namespace nimo_end_effector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nimo_end_effector::get_dat > {
  static const char* value()
  {
    return "94e2c8ba95addd945b6e068d063d8aa3";
  }

  static const char* value(const ::nimo_end_effector::get_dat&) { return value(); }
};

template<>
struct DataType< ::nimo_end_effector::get_dat > {
  static const char* value()
  {
    return "nimo_end_effector/get_dat";
  }

  static const char* value(const ::nimo_end_effector::get_dat&) { return value(); }
};


// service_traits::MD5Sum< ::nimo_end_effector::get_datRequest> should match
// service_traits::MD5Sum< ::nimo_end_effector::get_dat >
template<>
struct MD5Sum< ::nimo_end_effector::get_datRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nimo_end_effector::get_dat >::value();
  }
  static const char* value(const ::nimo_end_effector::get_datRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nimo_end_effector::get_datRequest> should match
// service_traits::DataType< ::nimo_end_effector::get_dat >
template<>
struct DataType< ::nimo_end_effector::get_datRequest>
{
  static const char* value()
  {
    return DataType< ::nimo_end_effector::get_dat >::value();
  }
  static const char* value(const ::nimo_end_effector::get_datRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nimo_end_effector::get_datResponse> should match
// service_traits::MD5Sum< ::nimo_end_effector::get_dat >
template<>
struct MD5Sum< ::nimo_end_effector::get_datResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nimo_end_effector::get_dat >::value();
  }
  static const char* value(const ::nimo_end_effector::get_datResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nimo_end_effector::get_datResponse> should match
// service_traits::DataType< ::nimo_end_effector::get_dat >
template<>
struct DataType< ::nimo_end_effector::get_datResponse>
{
  static const char* value()
  {
    return DataType< ::nimo_end_effector::get_dat >::value();
  }
  static const char* value(const ::nimo_end_effector::get_datResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIMO_END_EFFECTOR_MESSAGE_GET_DAT_H
