// Generated by gencpp from file nimo_end_effector/get_cal_datRequest.msg
// DO NOT EDIT!


#ifndef NIMO_END_EFFECTOR_MESSAGE_GET_CAL_DATREQUEST_H
#define NIMO_END_EFFECTOR_MESSAGE_GET_CAL_DATREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nimo_end_effector
{
template <class ContainerAllocator>
struct get_cal_datRequest_
{
  typedef get_cal_datRequest_<ContainerAllocator> Type;

  get_cal_datRequest_()
    : id()  {
    }
  get_cal_datRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_cal_datRequest_

typedef ::nimo_end_effector::get_cal_datRequest_<std::allocator<void> > get_cal_datRequest;

typedef boost::shared_ptr< ::nimo_end_effector::get_cal_datRequest > get_cal_datRequestPtr;
typedef boost::shared_ptr< ::nimo_end_effector::get_cal_datRequest const> get_cal_datRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator1> & lhs, const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator1> & lhs, const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nimo_end_effector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbfcda76036ebbe3d36caf7af80b260c";
  }

  static const char* value(const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbfcda76036ebbe3ULL;
  static const uint64_t static_value2 = 0xd36caf7af80b260cULL;
};

template<class ContainerAllocator>
struct DataType< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nimo_end_effector/get_cal_datRequest";
  }

  static const char* value(const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
;
  }

  static const char* value(const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_cal_datRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nimo_end_effector::get_cal_datRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIMO_END_EFFECTOR_MESSAGE_GET_CAL_DATREQUEST_H
