// Generated by gencpp from file nimo_end_effector/get_datRequest.msg
// DO NOT EDIT!


#ifndef NIMO_END_EFFECTOR_MESSAGE_GET_DATREQUEST_H
#define NIMO_END_EFFECTOR_MESSAGE_GET_DATREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nimo_end_effector
{
template <class ContainerAllocator>
struct get_datRequest_
{
  typedef get_datRequest_<ContainerAllocator> Type;

  get_datRequest_()
    {
    }
  get_datRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::nimo_end_effector::get_datRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nimo_end_effector::get_datRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_datRequest_

typedef ::nimo_end_effector::get_datRequest_<std::allocator<void> > get_datRequest;

typedef boost::shared_ptr< ::nimo_end_effector::get_datRequest > get_datRequestPtr;
typedef boost::shared_ptr< ::nimo_end_effector::get_datRequest const> get_datRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nimo_end_effector::get_datRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace nimo_end_effector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nimo_end_effector::get_datRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nimo_end_effector::get_datRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nimo_end_effector::get_datRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::nimo_end_effector::get_datRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nimo_end_effector/get_datRequest";
  }

  static const char* value(const ::nimo_end_effector::get_datRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::nimo_end_effector::get_datRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_datRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nimo_end_effector::get_datRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::nimo_end_effector::get_datRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NIMO_END_EFFECTOR_MESSAGE_GET_DATREQUEST_H
