// Generated by gencpp from file nimo_end_effector/get_cal_dat.msg
// DO NOT EDIT!


#ifndef NIMO_END_EFFECTOR_MESSAGE_GET_CAL_DAT_H
#define NIMO_END_EFFECTOR_MESSAGE_GET_CAL_DAT_H

#include <ros/service_traits.h>


#include <nimo_end_effector/get_cal_datRequest.h>
#include <nimo_end_effector/get_cal_datResponse.h>


namespace nimo_end_effector
{

struct get_cal_dat
{

typedef get_cal_datRequest Request;
typedef get_cal_datResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_cal_dat
} // namespace nimo_end_effector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nimo_end_effector::get_cal_dat > {
  static const char* value()
  {
    return "74ed4807db3aea6f5382bb427e2c235b";
  }

  static const char* value(const ::nimo_end_effector::get_cal_dat&) { return value(); }
};

template<>
struct DataType< ::nimo_end_effector::get_cal_dat > {
  static const char* value()
  {
    return "nimo_end_effector/get_cal_dat";
  }

  static const char* value(const ::nimo_end_effector::get_cal_dat&) { return value(); }
};


// service_traits::MD5Sum< ::nimo_end_effector::get_cal_datRequest> should match
// service_traits::MD5Sum< ::nimo_end_effector::get_cal_dat >
template<>
struct MD5Sum< ::nimo_end_effector::get_cal_datRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nimo_end_effector::get_cal_dat >::value();
  }
  static const char* value(const ::nimo_end_effector::get_cal_datRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nimo_end_effector::get_cal_datRequest> should match
// service_traits::DataType< ::nimo_end_effector::get_cal_dat >
template<>
struct DataType< ::nimo_end_effector::get_cal_datRequest>
{
  static const char* value()
  {
    return DataType< ::nimo_end_effector::get_cal_dat >::value();
  }
  static const char* value(const ::nimo_end_effector::get_cal_datRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nimo_end_effector::get_cal_datResponse> should match
// service_traits::MD5Sum< ::nimo_end_effector::get_cal_dat >
template<>
struct MD5Sum< ::nimo_end_effector::get_cal_datResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nimo_end_effector::get_cal_dat >::value();
  }
  static const char* value(const ::nimo_end_effector::get_cal_datResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nimo_end_effector::get_cal_datResponse> should match
// service_traits::DataType< ::nimo_end_effector::get_cal_dat >
template<>
struct DataType< ::nimo_end_effector::get_cal_datResponse>
{
  static const char* value()
  {
    return DataType< ::nimo_end_effector::get_cal_dat >::value();
  }
  static const char* value(const ::nimo_end_effector::get_cal_datResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIMO_END_EFFECTOR_MESSAGE_GET_CAL_DAT_H
